# Generated by Django 6.1 on 2026-08-12 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadAcreedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'entidad_acreedora',
            },
        ),
        migrations.CreateModel(
            name='EstadoDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'estado_deuda',
            },
        ),
        migrations.CreateModel(
            name='FuenteIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'fuente_ingreso',
            },
        ),
        migrations.CreateModel(
            name='TipoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'tipo_ingreso',
            },
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fecha_creacion', models.DateField()),
                ('entidad_acreedora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.entidadacreedora')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.estadodeuda')),
            ],
            options={
                'db_table': 'deuda',
            },
        ),
        migrations.CreateModel(
            name='PlanDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('cantidad_de_cuotas', models.IntegerField()),
                ('vigente', models.BooleanField(default=True)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.deuda')),
            ],
            options={
                'db_table': 'plan_de_pago',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fecha_vencimiento', models.DateField()),
                ('pagada', models.BooleanField(default=False)),
                ('plan_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.plandepago')),
            ],
            options={
                'db_table': 'cuota',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fecha', models.DateField()),
                ('fuente_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.fuenteingreso')),
                ('tipo_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.tipoingreso')),
            ],
            options={
                'db_table': 'ingreso',
            },
        ),
    ]
