# Generated by Django 6.1 on 2026-08-12 12:27

import comprobantes.funciones_auxiliares
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_comprobante',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_emision', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to=comprobantes.funciones_auxiliares.generar_ruta_comprobante)),
                ('tipo_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comprobantes.tipocomprobante')),
            ],
            options={
                'db_table': 'comprobante',
            },
        ),
    ]
