# Generated by Django 6.1 on 2026-08-12 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0001_initial'),
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='gasto_no_programado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gastos.gastonoprogramado'),
            preserve_default=False,
        ),
    ]
