# Generated by Django 6.1 on 2026-08-12 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        ('gastos', '0001_initial'),
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'medio_de_pago',
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'tipo_movimiento',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fecha', models.DateField()),
                ('medio_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movimientos.mediodepago')),
                ('tarjeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarjetas.tarjeta')),
                ('tipo_de_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movimientos.tipomovimiento')),
            ],
            options={
                'db_table': 'movimiento',
            },
        ),
        migrations.CreateModel(
            name='IngresoAplicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.ingreso')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.movimiento')),
            ],
            options={
                'db_table': 'ingreso_aplicado',
            },
        ),
        migrations.CreateModel(
            name='PagoAplicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.movimiento')),
            ],
            options={
                'db_table': 'pago_aplicado',
            },
        ),
        migrations.CreateModel(
            name='PagoAplicadoCuota',
            fields=[
                ('pagoaplicado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movimientos.pagoaplicado')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.cuota')),
            ],
            options={
                'db_table': 'pago_aplicado_cuota',
            },
            bases=('movimientos.pagoaplicado',),
        ),
        migrations.CreateModel(
            name='PagoAplicadoGasto',
            fields=[
                ('pagoaplicado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movimientos.pagoaplicado')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gastos.gasto')),
            ],
            options={
                'db_table': 'pago_aplicado_gasto',
            },
            bases=('movimientos.pagoaplicado',),
        ),
        migrations.CreateModel(
            name='PagoAplicadoResumenTarjeta',
            fields=[
                ('pagoaplicado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movimientos.pagoaplicado')),
                ('resumen_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarjetas.resumentarjetacredito')),
            ],
            options={
                'db_table': 'pago_aplicado_resumen_tarjeta',
            },
            bases=('movimientos.pagoaplicado',),
        ),
    ]
