# Generated by Django 6.1 on 2026-08-12 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenTarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagado', models.BooleanField(default=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='tarjetas/resumenes/')),
            ],
            options={
                'db_table': 'resumen_tarjeta_credito',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('entidad_emisora', models.CharField(max_length=100)),
                ('ultimos_4_digitos', models.CharField(max_length=4)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tarjeta',
            },
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('tarjeta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarjetas.tarjeta')),
                ('limite_credito', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_cierre', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'db_table': 'tarjeta_credito',
            },
            bases=('tarjetas.tarjeta',),
        ),
        migrations.CreateModel(
            name='TarjetaDebito',
            fields=[
                ('tarjeta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarjetas.tarjeta')),
                ('banco_asociado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tarjeta_debito',
            },
            bases=('tarjetas.tarjeta',),
        ),
        migrations.CreateModel(
            name='ConsumoTarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuota_actual', models.IntegerField(default=1)),
                ('cuotas_totales', models.IntegerField(default=1)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.gasto')),
                ('resumen_tarjeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarjetas.resumentarjetacredito')),
                ('tarjeta_credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarjetas.tarjetacredito')),
            ],
            options={
                'db_table': 'consumo_tarjeta_credito',
            },
        ),
    ]
