# Generated by Django 6.1 on 2026-08-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedida',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
