# Generated by Django 6.1 on 2026-08-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_unidadmedida_abreviatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='direccion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
