# Generated by Django 6.1 on 2026-08-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_comercio_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
