# Generated by Django 6.1 on 2026-08-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='categoria_gasto/iconos/')),
            ],
            options={
                'db_table': 'categoria_gasto',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=124)),
                ('fecha_hora', models.DateTimeField()),
                ('categoria_gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gastos.categoriagasto')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compras.compra')),
            ],
            options={
                'db_table': 'gasto',
            },
        ),
        migrations.CreateModel(
            name='GastoNoProgramado',
            fields=[
                ('gasto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gastos.gasto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                'db_table': 'gasto_no_programado',
            },
            bases=('gastos.gasto',),
        ),
        migrations.CreateModel(
            name='GastoProgramado',
            fields=[
                ('gasto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gastos.gasto')),
                ('monto_estimado', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gasto_programado',
            },
            bases=('gastos.gasto',),
        ),
    ]
