# Generated by Django 6.1 on 2026-08-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriagasto',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='categoria_gasto/iconos/'),
        ),
    ]
